### PR TITLE
Builds and runs an example on ubuntu podman container with gcc-12

### LINKED ISSUE #5: Failed To Build On Linux With Unsafe Cast `int`/`GLuint` to `void*`
Wanted to say this seems like a library with some potential! I wish I had could have used something like this when I was younger, there was  something called SF3D but I never got far with it.

GCC-12 on Ubuntu (in podman container) errors on a couple of casts in Scene.cpp 

I created this patch file in the [conan recipe I wrote](https://github.com/TheFloatingBrain/community/tree/main/recipes/dimension3d) in order to fix this problem (lines 449 and 451: 

```C++
diff --git a/Dimension3D/sources/windows/Scene.cpp b/Dimension3D/sources/windows/Scene.cpp
index 62b5499..3fa36d8 100644
--- a/Dimension3D/sources/windows/Scene.cpp
+++ b/Dimension3D/sources/windows/Scene.cpp
@@ -446,9 +446,9 @@ namespace dim
 		active = ImGui::IsWindowFocused();
 
 		ImGui::SetCursorPos(ImVec2(8.f, 27.f));
-		ImGui::Image(frame_buffer.get_texture().get_id(), ImVec2(static_cast<float>(temp.x), static_cast<float>(temp.y)), ImVec2(0.f, 1.f), ImVec2(1.f, 0.f));
+		ImGui::Image((void*) frame_buffer.get_texture().get_id(), ImVec2(static_cast<float>(temp.x), static_cast<float>(temp.y)), ImVec2(0.f, 1.f), ImVec2(1.f, 0.f));
 		ImGui::SetCursorPos(ImVec2(8.f, 27.f));
-		ImGui::Image(render_texture.getTexture().getNativeHandle(),
+		ImGui::Image((void*) render_texture.getTexture().getNativeHandle(),
 			ImVec2(static_cast<float>(render_texture.getTexture().getSize().x),
 			static_cast<float>(render_texture.getTexture().getSize().y)), ImVec2(0.f, 1.f), ImVec2(1.f, 0.f));
```

However it still throws a warning.

### PR DESCRIPTION
**Pull request by TheFloatingBrain**
Bug squashing fixes #5 and #6

### CODE REVIEW

**Comment by angeluriot** [comment]
*texture2D* was deprecated, but your other modification does not compile on my computer

**Comment by TheFloatingBrain** [comment]
> _texture2D_ was deprecated, but your other modification does not compile on my computer

Oh dear :laughing: How to resolve this in a standard compliant way without undefined behavior?

What OS + Compiler are you using, also what standard, I compiled with C++20

**Comment by angeluriot** [comment]
I use MSVC on Windows with C++17.

**Comment by Lecrapouille** [comment]
Same compilation error (strangely not happening with CMake). See https://github.com/ocornut/imgui/issues/1848

**Pull request closed without merging**
